services:
  - type: web
    name: laravel-weather-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: service nginx start && php-fpm
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: OPENWEATHERMAP_API_KEY
        sync: false
